# Generated by Django 5.1.1 on 2024-09-23 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=400, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=400, null=True, unique=True)),
                ('short_desc', models.CharField(help_text='Course description should be less than 600 charecter.', max_length=600)),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Regular Price')),
                ('off_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Discounted Price')),
                ('level', models.CharField(blank=True, choices=[('B', 'Begainer'), ('I', 'Intermediate'), ('A', 'Advance'), ('E', 'Expert')], default=None, max_length=10, null=True, verbose_name='Difficulty Level')),
                ('thumbnail', models.ImageField(upload_to='course/thumb/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.category', verbose_name='Choose Categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
