# Generated by Django 5.1.1 on 2024-09-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='off_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Discounted Price'),
        ),
    ]
