# Generated by Django 5.1.1 on 2024-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0005_remove_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_video',
            field=models.FileField(null=True, upload_to='course/video/'),
        ),
    ]
