# Generated by Django 5.1.1 on 2024-09-24 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_facebook_url_user_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='S', max_length=2),
        ),
        migrations.CreateModel(
            name='EducatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook profile URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter profile URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn profile URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram profile URL')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'E'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
