# Generated by Django 5.1.1 on 2024-09-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_facebook_url_remove_user_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('E', 'Educator'), ('S', 'Student')], default='S', max_length=2),
        ),
    ]
